name: tipdrop_mobile
description: Flutter primary app for TipDrop.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  go_router: ^17.2.3
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  image_picker: ^1.2.2
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
